### ISSUE TITLE
Objects management 2.4.0 - adding new object

### ISSUE THREAD

**Issue by shercargo** [TECLIB/genericobject#18]
When adding new object, the name of Internal identifier is broken after saving. For example: if we try to add new object 'tools', will be added 'tool'; 'instruments' will be 'instrument' etc...
We cant use cyrillic words in the name of Internal identifier, like 'Инструменты' (tools) - error appears: "Type must start with a letter". Can it be corrected in future?

**Comment by neeftarah** [comment]
NB : the 2.4.0 version was unstable and shouldn't has been created. It has been removed immediately.
Congratulation, you have been very fast to take it.
Thanks for your help identifying those very important bugs, but, please, consider you use a development version.

We will try to fix it in the next version, but we should make tests before. Indeed, this error occurs because genericobject plugin must create files when adding an object. In order to avoid problems, developers allows only ASCII letters in the object name.
After a first rapid test, it shouldn't be a problem to have cyrillic words in the name as soon as the system accept it.

The test should be done on file creation and not in object name.

**Comment by wawax** [comment]
Hello,

Create the itemtype by using a latin word (in your example tool).
Then go to glpi/files/_plugins/genericobject/locales/tool/ and edit the language file associated to your itemtype. Put the cyrillic word Инструменты in it, and it's going to be ok.
